#! /bin/bash

# Runs the given command line argument, then if there
# are filesystem changes (like when you save a file)
# run the command again (and again)...
#
# Example:
#    gowatch go test

clear
"$@" &

cleanup(){
	# Kill all child process but not myself:
	kill -9 $(
		ps -o pid -o pgid |
		grep $$ |
		awk '{print $1}' |
		grep -v $$
	) &> /dev/null
}

trap 'cleanup;exit' SIGINT

while inotifywait -e modify .;do
	cleanup
	clear
	"$@" &
done
