#! /bin/bash

# Runs the given command line argument, then if there
# are filesystem changes (like when you save a file)
# run the command again (and again)...
#
# Example:
#     gowatch go test
#
# If you need to run several commands in sequence then
# you need to quote them and pass them as a single
# argument (to avoid the shell interpreting the `;`
# character.
#
# Example:
#     gowatch 'goimports -w .;gorun'

run(){
	clear
	if [ "$#" -gt 1 ];then
		"$@" &
	else
		eval "$* &"
	fi
}

cleanup(){
	# Kill all child process but not myself:
	kill -9 $(
		ps -o pid -o pgid |
		grep $$ |
		awk '{print $1}' |
		grep -v $$
	) &> /dev/null
}

trap 'cleanup;exit' SIGINT

run "$@"
while inotifywait -e modify .;do
	cleanup
	run "$@"
done
